name: site deployment

on:
  workflow_dispatch:
  push:
      branches:
          - master
          - test
          - platform_installations
jobs:
    cleanup:
        if: ${{ github.ref_name == 'platform_cleanup' }}
        runs-on: self-hosted
        steps: 
          - name: "remove the instance created by terraform"
            run: |
              cd ~
              terraform destroy --auto-approve


            





              



            


        

