name: site deployment

on:
  workflow_run:
  push:
      branches:
          - master
          - test
          - platform_installations
jobs:
    preparation:

        if: ${{ github.ref_name == 'platform_installations' }}
        runs-on: self-hosted
        steps:
            - name: checks out
              uses: actions/checkout@v4

            - name: install dependencies
              run: bash _installations/install.sh

            - name: setup aws cli
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
                aws-region: eu-west-2
                aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}

            





              



            


        

