name: site deployment
on:
    push:
        branches:
            - master
            - test
            - platform_installations
jobs:
    preparation:

        if: ${{ github.ref_name == 'platform_installations' }}
        runs-on: self-hosted
        steps:
            - name: checks out
              uses: actions/checkout@v4
              
            - name: install dependencies
              run: bash _installations/install.sh





              



            


        

